// Code generated by go-swagger; DO NOT EDIT.

package math

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddReader is a Reader for the Add structure.
type AddReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAddUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddOK creates a AddOK with default headers values
func NewAddOK() *AddOK {
	return &AddOK{}
}

/*AddOK handles this case with default header values.

Sum of two integers.
*/
type AddOK struct {
	Payload *AddOKBody
}

func (o *AddOK) Error() string {
	return fmt.Sprintf("[GET /add][%d] addOK  %+v", 200, o.Payload)
}

func (o *AddOK) GetPayload() *AddOKBody {
	return o.Payload
}

func (o *AddOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AddOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddUnauthorized creates a AddUnauthorized with default headers values
func NewAddUnauthorized() *AddUnauthorized {
	return &AddUnauthorized{}
}

/*AddUnauthorized handles this case with default header values.

Unauthorized
*/
type AddUnauthorized struct {
}

func (o *AddUnauthorized) Error() string {
	return fmt.Sprintf("[GET /add][%d] addUnauthorized ", 401)
}

func (o *AddUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddForbidden creates a AddForbidden with default headers values
func NewAddForbidden() *AddForbidden {
	return &AddForbidden{}
}

/*AddForbidden handles this case with default header values.

Forbidden
*/
type AddForbidden struct {
}

func (o *AddForbidden) Error() string {
	return fmt.Sprintf("[GET /add][%d] addForbidden ", 403)
}

func (o *AddForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddInternalServerError creates a AddInternalServerError with default headers values
func NewAddInternalServerError() *AddInternalServerError {
	return &AddInternalServerError{}
}

/*AddInternalServerError handles this case with default header values.

Unexpected error
*/
type AddInternalServerError struct {
}

func (o *AddInternalServerError) Error() string {
	return fmt.Sprintf("[GET /add][%d] addInternalServerError ", 500)
}

func (o *AddInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*AddOKBody add o k body
swagger:model AddOKBody
*/
type AddOKBody struct {

	// res
	Res int64 `json:"res"`
}

// Validate validates this add o k body
func (o *AddOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AddOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddOKBody) UnmarshalBinary(b []byte) error {
	var res AddOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
