// Code generated by go-swagger; DO NOT EDIT.

package math

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSubtractParams creates a new SubtractParams object
// with the default values initialized.
func NewSubtractParams() *SubtractParams {
	var ()
	return &SubtractParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSubtractParamsWithTimeout creates a new SubtractParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSubtractParamsWithTimeout(timeout time.Duration) *SubtractParams {
	var ()
	return &SubtractParams{

		timeout: timeout,
	}
}

// NewSubtractParamsWithContext creates a new SubtractParams object
// with the default values initialized, and the ability to set a context for a request
func NewSubtractParamsWithContext(ctx context.Context) *SubtractParams {
	var ()
	return &SubtractParams{

		Context: ctx,
	}
}

// NewSubtractParamsWithHTTPClient creates a new SubtractParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSubtractParamsWithHTTPClient(client *http.Client) *SubtractParams {
	var ()
	return &SubtractParams{
		HTTPClient: client,
	}
}

/*SubtractParams contains all the parameters to send to the API endpoint
for the subtract operation typically these are written to a http.Request
*/
type SubtractParams struct {

	/*A*/
	A int64
	/*B*/
	B int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the subtract params
func (o *SubtractParams) WithTimeout(timeout time.Duration) *SubtractParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the subtract params
func (o *SubtractParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the subtract params
func (o *SubtractParams) WithContext(ctx context.Context) *SubtractParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the subtract params
func (o *SubtractParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the subtract params
func (o *SubtractParams) WithHTTPClient(client *http.Client) *SubtractParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the subtract params
func (o *SubtractParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithA adds the a to the subtract params
func (o *SubtractParams) WithA(a int64) *SubtractParams {
	o.SetA(a)
	return o
}

// SetA adds the a to the subtract params
func (o *SubtractParams) SetA(a int64) {
	o.A = a
}

// WithB adds the b to the subtract params
func (o *SubtractParams) WithB(b int64) *SubtractParams {
	o.SetB(b)
	return o
}

// SetB adds the b to the subtract params
func (o *SubtractParams) SetB(b int64) {
	o.B = b
}

// WriteToRequest writes these params to a swagger request
func (o *SubtractParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param a
	qrA := o.A
	qA := swag.FormatInt64(qrA)
	if qA != "" {
		if err := r.SetQueryParam("a", qA); err != nil {
			return err
		}
	}

	// query param b
	qrB := o.B
	qB := swag.FormatInt64(qrB)
	if qB != "" {
		if err := r.SetQueryParam("b", qB); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
