// Code generated by go-swagger; DO NOT EDIT.

// Package restapi CalcApp
//
//  Simple calc api for mathematical add and subtract.
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
