// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Simple calc api for mathematical add and subtract.",
    "title": "CalcApp",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/add": {
      "get": {
        "tags": [
          "math"
        ],
        "summary": "Get sum of two integers, x and y, as a result.",
        "operationId": "add",
        "parameters": [
          {
            "type": "integer",
            "name": "a",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "name": "b",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Sum of two integers.",
            "schema": {
              "type": "object",
              "properties": {
                "res": {
                  "type": "integer",
                  "x-omitempty": false
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Unexpected error"
          }
        }
      }
    },
    "/subtract": {
      "get": {
        "tags": [
          "math"
        ],
        "summary": "Get subtract of two integers, x and y, as a result.",
        "operationId": "subtract",
        "parameters": [
          {
            "type": "integer",
            "name": "a",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "name": "b",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "subtract of two integers.",
            "schema": {
              "type": "object",
              "properties": {
                "res": {
                  "type": "integer",
                  "x-omitempty": false
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Unexpected error"
          }
        }
      }
    }
  },
  "definitions": {
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "APIKeyHeader": {
      "type": "apiKey",
      "name": "X-API-Key",
      "in": "header"
    }
  },
  "security": [
    {
      "APIKeyHeader": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Simple calc api for mathematical add and subtract.",
    "title": "CalcApp",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/add": {
      "get": {
        "tags": [
          "math"
        ],
        "summary": "Get sum of two integers, x and y, as a result.",
        "operationId": "add",
        "parameters": [
          {
            "type": "integer",
            "name": "a",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "name": "b",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Sum of two integers.",
            "schema": {
              "type": "object",
              "properties": {
                "res": {
                  "type": "integer",
                  "x-omitempty": false
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Unexpected error"
          }
        }
      }
    },
    "/subtract": {
      "get": {
        "tags": [
          "math"
        ],
        "summary": "Get subtract of two integers, x and y, as a result.",
        "operationId": "subtract",
        "parameters": [
          {
            "type": "integer",
            "name": "a",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "name": "b",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "subtract of two integers.",
            "schema": {
              "type": "object",
              "properties": {
                "res": {
                  "type": "integer",
                  "x-omitempty": false
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Unexpected error"
          }
        }
      }
    }
  },
  "definitions": {
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "APIKeyHeader": {
      "type": "apiKey",
      "name": "X-API-Key",
      "in": "header"
    }
  },
  "security": [
    {
      "APIKeyHeader": []
    }
  ]
}`))
}
