// Code generated by go-swagger; DO NOT EDIT.

package math

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddOKCode is the HTTP code returned for type AddOK
const AddOKCode int = 200

/*AddOK Sum of two integers.

swagger:response addOK
*/
type AddOK struct {

	/*
	  In: Body
	*/
	Payload *AddOKBody `json:"body,omitempty"`
}

// NewAddOK creates AddOK with default headers values
func NewAddOK() *AddOK {

	return &AddOK{}
}

// WithPayload adds the payload to the add o k response
func (o *AddOK) WithPayload(payload *AddOKBody) *AddOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add o k response
func (o *AddOK) SetPayload(payload *AddOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddUnauthorizedCode is the HTTP code returned for type AddUnauthorized
const AddUnauthorizedCode int = 401

/*AddUnauthorized Unauthorized

swagger:response addUnauthorized
*/
type AddUnauthorized struct {
}

// NewAddUnauthorized creates AddUnauthorized with default headers values
func NewAddUnauthorized() *AddUnauthorized {

	return &AddUnauthorized{}
}

// WriteResponse to the client
func (o *AddUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddForbiddenCode is the HTTP code returned for type AddForbidden
const AddForbiddenCode int = 403

/*AddForbidden Forbidden

swagger:response addForbidden
*/
type AddForbidden struct {
}

// NewAddForbidden creates AddForbidden with default headers values
func NewAddForbidden() *AddForbidden {

	return &AddForbidden{}
}

// WriteResponse to the client
func (o *AddForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// AddInternalServerErrorCode is the HTTP code returned for type AddInternalServerError
const AddInternalServerErrorCode int = 500

/*AddInternalServerError Unexpected error

swagger:response addInternalServerError
*/
type AddInternalServerError struct {
}

// NewAddInternalServerError creates AddInternalServerError with default headers values
func NewAddInternalServerError() *AddInternalServerError {

	return &AddInternalServerError{}
}

// WriteResponse to the client
func (o *AddInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
